spring:
  application:
    name: market_service
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/trading_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true

server:
  port: 9095

logging:
  level:
    org:
      hibernate:
        SQL: debug